site_name: apsimNGpy Documentation
theme:
  name: 'material'

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
      - Basic Tutorial: tutorials/basic.md
      - Advanced Tutorial: tutorials/advanced.md
  - API Reference: api.md
